---
app_user: "places"
app_user_password: "P@ssw0rd"
app_user_directory: "/home/places"
app_directory: "/home/places/Places"
app_client_directory: "{{ app_directory }}/src/client"
app_service_template_src: "places.service.j2"
app_service_template_dest: "/etc/systemd/system/places.service"
application_github_link: "https://github.com/WongDerek94/Places.git"
map_container_js: "MapContainer.js"
map_container_dest_location: "{{ app_directory }}/src/client/src/components"
db_host: "localhost"
db_port: "3306"
db_user: "root"
db_pass: "P@ssw0rd"
db_name: "maps"
env_file: ".env.j2"
env_file_dest: "{{ app_directory }}/src/.env"
...