---
- name: "Check if nodejs is installed"
  package_facts:
    manager: "auto"

- name: "Set nodejs version to 10"
  shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"
  args:
    warn: false
  when: "'nodejs' not in ansible_facts.packages"

- name: "Install nodejs"
  package:
    name: "nodejs"
    state: "latest"
  when: "'nodejs' not in ansible_facts.packages"

- name: "Install create-react-app package globally"
  npm:
    name: "create-react-app"
    global: yes
    state: "present"
...