---
- name: Install nodejs and npm
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - epel-release
    - nodejs
    - npm
- name: Install create react app package globally
  npm:
    name: create-react-app
    global: yes
...